# Generated by Django 4.0.1 on 2022-01-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='type',
            field=models.CharField(choices=[('TOG', 'Должны попасть на один проект'), ('SEP', 'Не должны попасть на один проект')], default='ND', max_length=3, verbose_name='Тип ограничения'),
        ),
    ]
